language: python

python: 2.7

sudo: false

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

cache: pip

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

install:
  - pip install ansible

script:
  - ansible-playbook -i 'localhost,' --syntax-check tests/test.yml
