---
- user:
    name: hetrixtools
    group: sudo

- name: Modify HetrixTool agent
  template:
    src: hetrixtools_agent.sh.j2
    dest: "/etc/hetrixtools/hetrixtools_agent.sh"

- name: Let HetrixTools know we're setting everyting up
  uri:
    url: https://sm.hetrixtools.com/
    method: 'POST'
    body: v=install&s={{ wordpress_sites[item].hetrixtools.sid }}
  with_items: "{{ sites_using_hetrixtools }}"

- name: Add HetrixTools Agent Cronjob
  cron:
    name: "HetrixTools Agent Cronjob"
    job: "bash /etc/hetrixtools/hetrixtools_agent.sh >> /etc/hetrixtools/hetrixtools_cron.log 2>&1"
    user: hetrixtools
